### ISSUE TITLE
[2.dnscrypt-cert.dnscrypt.ca-2.] Incorrect signature

### ISSUE THREAD

**Issue by Mikaela** [DNSCrypt/dnscrypt-resolvers#62]
While using `public_resolvers.md` without server_names, I see `[2.dnscrypt-cert.dnscrypt.ca-2.] Incorrect signature` in `journalctl -u dnscrypt-proxy`.  Where does it come from?

There is no `2.dnscrypt-cert.dnscrypt.ca-2.` in the file and I don't see errors about them.

```
Dec 02 12:28:37 sedric dnscrypt-proxy[3156]: [dnscrypt.ca-1] OK (crypto v1) - rtt: 123ms
Dec 02 12:28:37 sedric dnscrypt-proxy[3156]: [dnscrypt.ca-2] OK (crypto v1) - rtt: 121ms
Dec 02 12:28:37 sedric dnscrypt-proxy[3156]: [2.dnscrypt-cert.dnscrypt.ca-2.] Incorrect signature
```

I have contacted the admin who doesn't have ideas either and cannot reproduce this issue by setting those servers as server_names and I am also only able to see this by having empty server_names.

* dnscrypt-proxy 2.0.19 (from Debian repositories)
* Debian GNU/Linux testing (buster)

**Comment by Mikaela** [comment]
Emailing with the admin more, we found out that the issue doesn't happen with config file:

```toml
listen_addresses = []
[sources]
  [sources.'public-resolvers']
  #url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md', 'https://cdn.staticaly.com/gh/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://evilvibes.com/list/public-resolvers.md']
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
```

but does happen with my [usual config](https://github.com/Mikaela/shell-things/blob/9be5b35b3292c933dbe9195686f206b76502671e/etc/dnscrypt-proxy/dnscrypt-proxy.toml).

Is there something drastically different in my config compared to the defaults? I think it's something related to my [require_ lines](https://github.com/Mikaela/shell-things/blob/9be5b35b3292c933dbe9195686f206b76502671e/etc/dnscrypt-proxy/dnscrypt-proxy.toml#L16-L21), but I don't think they explain this.
